<a href="https://colab.research.google.com/github/Bolorooo24/CV-ML_labs/blob/main/Pytorch-deep-learning/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


### 00 Pytorch fundamentals
Resource notebook:  https://www.learnpytorch.io/00_pytorch_fundamentals/

### Introduction to Tensors

#### Creating tensors

Pytorch tensors are created using torch.Tensor() = https://docs.pytorch.org/docs/stable/tensors.html


In [ ]:
import torch
print(torch.__version__)
scalar = torch.tensor(7)
scalar.ndim

2.8.0+cu126


0

In [ ]:
# get tensor back as python int
scalar.item()

7

In [ ]:
# vector
# ndim is the [] set of square brackets
# shape is number of elements
vector = torch.tensor([7,7])
vector.ndim

1

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,19]])
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2],
                        [4,5],
                        [1,2],
                        [3,6]]])
TENSOR.shape

torch.Size([1, 4, 2])

###Random tensors
Why random tensors?

It's important becuase the neural network learns is start with random numbers and look at data and update the random numbers and over and over again.

Torch random tensors - https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# create a random tensor of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2472, 0.5680, 0.0269, 0.2948],
        [0.3303, 0.9910, 0.7357, 0.9074],
        [0.3587, 0.9338, 0.1667, 0.9489]])

In [ ]:
# create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor

tensor([[[0.2752, 0.3909, 0.5808,  ..., 0.3439, 0.6961, 0.2471],
         [0.9678, 0.2784, 0.8285,  ..., 0.4722, 0.7257, 0.9831],
         [0.9147, 0.7263, 0.9650,  ..., 0.6752, 0.4926, 0.2472],
         ...,
         [0.2273, 0.3259, 0.5503,  ..., 0.0547, 0.3593, 0.9069],
         [0.6431, 0.8847, 0.4602,  ..., 0.4087, 0.1108, 0.7397],
         [0.1929, 0.7708, 0.6298,  ..., 0.9814, 0.7456, 0.9386]],

        [[0.6089, 0.1465, 0.0774,  ..., 0.1450, 0.5841, 0.2297],
         [0.9834, 0.9243, 0.6201,  ..., 0.9476, 0.9002, 0.6533],
         [0.0109, 0.5150, 0.3081,  ..., 0.5439, 0.8274, 0.7650],
         ...,
         [0.2796, 0.1637, 0.0875,  ..., 0.6673, 0.1749, 0.6028],
         [0.9136, 0.4662, 0.5230,  ..., 0.8013, 0.9385, 0.9616],
         [0.5342, 0.1860, 0.8757,  ..., 0.2967, 0.0688, 0.1159]],

        [[0.6153, 0.5217, 0.4142,  ..., 0.9055, 0.1069, 0.1798],
         [0.6850, 0.4833, 0.0915,  ..., 0.1135, 0.7987, 0.8884],
         [0.4371, 0.1784, 0.8943,  ..., 0.5062, 0.8589, 0.

####Zeros and ones

In [ ]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

#### Creating a range of tensors and tensors-like

In [ ]:
# use torch.range()
one_to_ten = torch.arange(start =1, end=100, step=20)
one_to_ten

tensor([ 1, 21, 41, 61, 81])

In [ ]:
# tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

####Tensor datatypes

**None:** Tensor datatypes is one of the 3 big error you'll run into with pytorch & deep learning:

1. Tensors not right datatype - what dataype is the tensor
2. Tensors not right shape - what device is your tensor on
3. Tensors not right device - whether or not to track gradients iwth this tensors operations


In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None, device=None, requires_grad=False)
float_32_tensor.dtype

torch.float32

In [ ]:
float_16 = float_32_tensor.type(torch.float16)
float_16

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_64 = torch.tensor([2.0, 2.0, 2.0], dtype=torch.float64)
float_64


tensor([2., 2., 2.], dtype=torch.float64)

In [ ]:
float_32_tensor*float_64

tensor([ 6., 12., 18.], dtype=torch.float64)

#### Getting information from tensors
1. Tensors not right datatype - tensor.dtype
2. Tensors not right shape - tensor.shape
3. Tensors not right device -tensor.device

In [ ]:
# create a tensor
some_tensor = torch.rand(2,4)

In [ ]:
# attributes with dot no brackets
print(some_tensor)
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.device)

tensor([[0.5896, 0.7521, 0.0030, 0.8633],
        [0.8838, 0.7772, 0.6456, 0.3927]])
torch.float32
torch.Size([2, 4])
cpu


In [ ]:
# function/method with brackets
some_tensor.size()

torch.Size([2, 4])

from re import sub
#### Manipulating tensors (tensor operations)
Tensor operation includes:
* add
* sub
* multiply
* divide
* matrix multi

There are 2 main rules in matrix multiplication.
1. The **inner dimensions** must match
* (3,2)@(3,2) won't work
* (2,3)@(3,2) will work
2. The result matrix has the shape of the outer dimensions.
* (2,3)@(3,2) => (2,2)

In [ ]:
tensor = torch.tensor([1,2,3])

tensor


tensor([1, 2, 3])

####Matrix multiplication
2 main ways of performing multi in NN and DL
1. element wise
2. matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [ ]:
# Element wise
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# matrix multi
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value = value + tensor[i]*tensor[i]
print(value)


tensor(14)
CPU times: user 1.66 ms, sys: 0 ns, total: 1.66 ms
Wall time: 5.88 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 71 µs, sys: 12 µs, total: 83 µs
Wall time: 87.3 µs


tensor(14)

#### Common error in deep learning: shape error


In [ ]:
# shapes for matrix multi
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])



In [ ]:
tensor_B.shape, tensor_A.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our shape issues, we can manipulate the shape of one of our tensors using transpose

A **transpose** switches the axes or dimenstions of a given tensor

In [ ]:
tensor_B = tensor_B.T
tensor_B.shape, tensor_A.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [ ]:
# the matrix mul works when tensore

torch.matmul(tensor_A, tensor_B)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min,max,sum etc tensor aggregation

In [ ]:
# create a tensor
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
# find the mean - note: the torch.mean() function requires a tensor of float32 to work
torch.mean(x.type(torch.float32))

tensor(46.)

In [ ]:
# find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### Finding the positional min and max


In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# find the position in in tensor that has the min val with argmin() -> return the index of min value
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

### Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapres an input tensors to a defined Shape
* View - return a view of an input tensor of certainshape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other or side by side
* Squeeze - removes all 1 dimensions from a tensor
* Unsqueeze - add a 1 dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# create  a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
9# add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# changing z changes x because a view of a tensor shares the same memory as the original input
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
print(f"previous tensor: {x_reshaped}")
print(f"previous shape: {x_reshaped.shape}")

# remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
# squeeze removes all simple dimensions
x_squeeze = torch.squeeze(x_reshaped)
x_squeeze.shape

torch.Size([9])

In [ ]:
# unsqueeze - adds a single dimension to a target tensor at a specific dim
print(f"previous target: {x_squeeze}")
print(f"previous shape: {x_squeeze.shape}")

# add an extra dimension with unsqueeze
x_unsqueezed = x_squeeze.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")
x_unsqueezed2 = x_unsqueezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed2}")
print(f"New shape: {x_unsqueezed2.shape}")

previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])

New tensor: tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]])
New shape: torch.Size([1, 1, 9])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
# https://docs.pytorch.org/docs/stable/generated/torch.permute.html

x_org = torch.rand(size=(224,224,3)) # height, width, colour_channel
# permute the org tensor to rearrange the axis/dim order
# it shares same memory as original tensor memory
x_permuted =  x_org.permute(2, 0, 1)
print(f"previous shape: {x_org.shape}")
print(f"New shape: {x_permuted.shape}")

previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_org[0,0,:]

tensor([0.4548, 0.2668, 0.4826])

### Indexing(selecting data from tensors)
Indexing with pytorch is similar to indexing with numpy

In [ ]:
# create a tensor
import torch
x = torch.arange(1, 10)
x
x_reshaped = x.reshape(1,3,3)
x, x_reshaped


(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]))

In [ ]:
# lets index on our new tensor
x_reshaped[0][2][2]


tensor(9)

In [ ]:
# you can also use ":" to select all of a target dimension
x_reshaped[:,2:,2]

tensor([[9]])

In [ ]:
# get all values of the 0 dimension but only the 1 index value of the 1st and the 2nd dim
x_reshaped[:, 1, 1] # ":" represent selecting all the element of the dimension

tensor([5])

In [ ]:
# get index - of -th and 1st dimension and all values of 2nd dim
x_reshaped[0, 2, 2]

tensor(9)

### Pytorch tesnsors & Numpy
Numpy is a popular scientifiv python numerical computing lib.
And because of this, pytorch has func to interact with iteract with iter
* Data in Numpy, want in Pytorch tensor -> torch.from_numpy(ndarray)
* Pytorch tensor -> Numpy -> torch.Tensor.numpy()

* Numpy default dtype = float64
* Tensor default dtype = float32

https://docs.pytorch.org/tutorials/beginner/examples_tensor/polynomial_numpy.html

In [ ]:
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # specify the datatype float64 or float32
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# change the value of array, what will this do to tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (trying to take random out of random)
In short how a neural network learns:
start with random numbers -> tensor operations -> update random numbers to try and make them better represntantion of the data -> again.

To reduce the randomness in neural networkds and Pytorch comes the concept of a random seet.

Essentially what the random seed does is flavour the randomness.


https://docs.pytorch.org/docs/stable/generated/torch.manual_seed.html


https://docs.pytorch.org/docs/stable/notes/randomness.html



In [ ]:
import torch

# create 2 random tensors

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2454, 0.8223, 0.3676, 0.7807],
        [0.8609, 0.6536, 0.2990, 0.7852],
        [0.0702, 0.4150, 0.4619, 0.2849]])
tensor([[0.5616, 0.7860, 0.0976, 0.4580],
        [0.7227, 0.1410, 0.9673, 0.3575],
        [0.0437, 0.6039, 0.5667, 0.6484]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# lets make random reproducable tensors
import torch
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and Pytorch objects on the GPUs and making faster computations
GPUs = faster computation on numbers, CUDA + NVIDIA hardware + PyTorch working behind the scenes

#### 1. Getting a GPU
1. easiest  - use google colab pro
2. use your own GPU- see this post https://timdettmers.com/category/deep-learning/
3. use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them


For 2, 3 pytorch + gpu drives takes a setting up, to do this, refer to pytorch setup documentation:

https://pytorch.org/get-started/locally/

In [ ]:
!nvidia-smi

Tue Oct 21 01:45:24 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   62C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
#  check for gpu access with pytorch
import torch
torch.cuda.is_available()

True

In [ ]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

For pytorch since ti's capable of running compute on the gpu and cpu, its best practice to setup device agnostic code: https://docs.pytorch.org/docs/stable/notes/cuda.html

In [ ]:
# count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors and models on the GPU
The reason we want ou tensors/models on the gpu is because using a gpu results in faster operations

In [ ]:
# create a tensor default on the cpu
tensor = torch.tensor([1, 2, 3])

# tensor not on gpu
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# move tensor to gpu if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. moving tensors back to the gpu


In [ ]:
# to fix the gpu tensor with numpy issue, we can fist set it to the gpu
tensor_on_gpu = tensor_on_gpu.cpu().numpy()
tensor_on_gpu

array([1, 2, 3])

In [ ]:
### Exercises & extra curriculum